name: Maven Package

on:
  push:
    branches:
      - LucasPinheiro

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Valor do campo distributionManagement/repository/id do pom.xml
        settings-path: ${{ github.workspace }} # localização do arquivo settings.xml

    - name: Maven Clean
      run: mvn -B clean --file pom.xml

    - name: Maven Install without Tests
      run: mvn -B install -DskipTests --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
