name: Build on Push

on:
  push:
    branches: [ "LucasPinheiro" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Limpar projeto com Maven
        run: mvn clean

      - name: Instalar dependencias com Maven pulando os testes
        run: mvn install -DskipTests
        
